### ISSUE TITLE
尝试使用了下还是会存在截图权限无法点击确定按钮的情况

### ISSUE THREAD

**Issue by msccreater** [TonyJiangWJ/AutoScriptBase#10]

**Comment by TonyJiangWJ** [comment]
具体是什么表现？是不是配置的文本不正确

**Comment by MinezzZ** [comment]
> 具体是什么表现？是不是配置的文本不正确

我用自己写的脚本时也遇到过这个问题。具体表现就是点击不动按钮。怎么点击屏幕依旧还是处于确认/取消的请求页面。锁屏之后重新运行脚本就OK，估计是miui的系统bug，而与脚本无关。

**Comment by TonyJiangWJ** [comment]
最近也遇到了，关闭悬浮窗之后就能点击了。
感觉是MIUI的bug 以前有个版本无障碍的确定按钮也会被悬浮窗挡住无法点击，但是那个版本会toast提醒关闭悬浮窗
