### ISSUE TITLE
支持热更新功能

### ISSUE THREAD

**Issue by tkkcc** [TonyJiangWJ/AutoScriptBase#11]
热更新可以免去用户手动点击下载安装启动app或者手动更新脚本的过程，在手游这种迭代周期短的场景中有需求。大部分图色脚本平台（按键精灵、节点精灵、EasyClick、hamibot）都有提供。启动时可以下载一个版本号与更新类别，如果有新版本且只需更新脚本，就下载打包后的脚本，解压后再运行。更新源可以白嫖gitee，gitee支持镜像github，打包可以白嫖action。希望大佬考虑下~

**Comment by TonyJiangWJ** [comment]
功能已经有了 无非是把现有的手动更新改成自动更新，只是我这边没这个需求 就没做 你有需要的话修改对应代码就行了
这个仓库我完全看心情更新的，等我的话可能不知道要等到什么时候。

**Comment by tkkcc** [comment]
原来已经有了，刚才没仔细看。太强了！
