### ISSUE TITLE
hamibot修改了auto，增加了ocr，参考一下能不能也增加这个功能

### ISSUE THREAD

**Issue by keep-an** [TonyJiangWJ/AutoScriptBase#12]

**Comment by TonyJiangWJ** [comment]
那你直接加就行了呀 我这个又不用hamibot。。

**Comment by keep-an** [comment]
我意思是autojs是不是也可以增加这个功能

**Comment by TonyJiangWJ** [comment]
拜托 这个仓库是脚本仓库 不是AutoJs 你说的功能需要修改的是AutoJS的代码 而不是这个仓库里面的脚本。AutoJs官方有OCR插件 不一定需要修改源代码 具体对接你可以去看下 https://pro.autojs.org/docs/#/zh-cn/plugins?id=ocr%e6%8f%92%e4%bb%b6

**Comment by keep-an** [comment]
好的 明白了 非常感谢
