### ISSUE TITLE
请问一下你这修改版的打包用哪个插件？

### ISSUE THREAD

**Issue by heham** [TonyJiangWJ/AutoScriptBase#13]
如题，按提示的那个275不能下载

**Comment by TonyJiangWJ** [comment]
打包插件我没做开发，因为是本着脚本开源使用的目的来修改的，用户可以只安装autojs即可使用多个脚本

**Comment by heham** [comment]
好的，谢谢解惑，打包对我来说可有可无，我的脚本也都是在app里运行

**Comment by TonyJiangWJ** [comment]
你来这边问是因为那边关闭了ISSUE吗 我才发现没打开🤣
