### ISSUE TITLE
[问题]QQ无法获取节点，一直提示：获取根节点失败 退出执行 请检查无障碍是否正常

### ISSUE THREAD

**Issue by tasbox** [TonyJiangWJ/AutoScriptBase#17]
QQ无法获取节点，一直提示：获取根节点失败 退出执行 请检查无障碍是否正常
手机：鸿蒙
模式：开发模式

**Comment by TonyJiangWJ** [comment]
用的Pro? Pro自带屏蔽 别折腾了

**Comment by tasbox** [comment]
好的，谢谢你。我的确用的PRo8.2版本。


| |
Asal
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月9日 09:34 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [TonyJiangWJ/AutoScriptBase] [问题]QQ无法获取节点，一直提示：获取根节点失败 退出执行 请检查无障碍是否正常 (Issue #17) |

用的Pro? Pro自带屏蔽 别折腾了
