### ISSUE TITLE
SQLliteUtils如何使用

### ISSUE THREAD

**Issue by lambertwe** [TonyJiangWJ/AutoScriptBase#18]
SQLiteUtils是否可以提供一下例子

**Comment by TonyJiangWJ** [comment]
你参考蚂蚁森林和聚合签到吧

**Comment by lambertwe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lambertwe** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
