### ISSUE TITLE
[Error ]  异常终止的重启任务已存在: [{"mAction":"org.autojs.autojs.action.startup","mLocal":true,"mScriptPath":"/data/user/0/org.autojs.autojspro/cache/remote_project/acb3eab1e2bc953917945eef30d50579/lib/prototype/CrashCatcher.js"}]

### ISSUE THREAD

**Issue by PLQin** [TonyJiangWJ/AutoScriptBase#2]
![image](https://user-images.githubusercontent.com/24371471/94413235-65927880-01ad-11eb-8c52-242b4afdcfbc.png)

这段代码的提示指的是 "org.autojs.autojs.action.startup" 没有正常重启吗? 

如果做能使得它正常重启呢 ? ( 我尝试过关闭autojs然后重新打开, 但仍然是这个错误 )

**Comment by TonyJiangWJ** [comment]
不用管，已经创建了。只需要给AutoJS自启动权限即可保证脚本全时段稳定运行。

脚本中灰色字体的都是调试日志，这些日志都是帮助排查问题用的，日常来说不用太多关注。其对应的是verbose，也就是你截图里面 `HH:mm:ss.S/V:` 所对应的日志。你可以运行config.js 取消勾选显示DEBUG日志即可。
需要关注的仅仅是红色字体的ERROR的日志。

**Comment by PLQin** [comment]
OK !
