### ISSUE TITLE
执行控件可视化报错

### ISSUE THREAD

**Issue by Thinker-ljn** [TonyJiangWJ/AutoScriptBase#20]
![image](https://user-images.githubusercontent.com/8445972/224522998-cf7b512b-5139-4288-b8f7-293cd107e0ae.png)

大佬，有什么解决方法吗？或者说还要我提供什么让你排查一下？

下面是我的手机信息，华为MATE30
![image](https://user-images.githubusercontent.com/8445972/224523009-7918f3a3-d95e-4a5a-9b68-8e61d928ff4f.png)

**Comment by TonyJiangWJ** [comment]
这个不再使用了 手机端性能不足。 请使用PC端浏览器打开 index.html 脚本内的会删除
