### ISSUE TITLE
导入模块：[ProcessShare]失败，请检查代码

### ISSUE THREAD

**Issue by geekscloud** [TonyJiangWJ/AutoScriptBase#24]
autoJS中运行提示：导入模块：[ProcessShare]失败，请检查代码
项目太复杂了，新手有点吃力。
新手需要自动获取无障碍权限那段，希望作者有空的话能回复一下小白， 万分感谢。

**Comment by TonyJiangWJ** [comment]
不提供教学服务，可能你用的AutoJS版本太老或者不兼容，请下载这个：https://github.com/TonyJiangWJ/Ant-Forest/releases/download/v1.1.1.4/AutoJS.modify.latest.apk
另外，小白玩这个项目干嘛

**Comment by geekscloud** [comment]
> 不提供教学服务，可能你用的AutoJS版本太老或者不兼容，请下载这个：https://github.com/TonyJiangWJ/Ant-Forest/releases/download/v1.1.1.4/AutoJS.modify.latest.apk 另外，小白玩这个项目干嘛

也不算特别小白，我是搞后端的，不太了解前端， 这个autoJS刚玩，哈哈哈
想打包一个简单单JS脚本APK，能自动获取无障碍那段的代码，就行，如果有空的话愿意有偿。
因为刚研究所以卡在第一步，只需要简单的学习一下这个自动无障碍获取，已经知道需要ABD授权怎么搞了，但是还不明白这个获取服务名是怎么回事。

**Comment by geekscloud** [comment]
> 不提供教学服务，可能你用的AutoJS版本太老或者不兼容，请下载这个：https://github.com/TonyJiangWJ/Ant-Forest/releases/download/v1.1.1.4/AutoJS.modify.latest.apk 另外，小白玩这个项目干嘛

感谢，通过这个apk可以成跑起框架了，看起来没什么问题， 不过这个版本的打包插件似乎找不到，我有4.1.1的好像不行，辛苦可以提供一下吗， 或者加个微信详聊，愿意付费虚心学习。
只需要学习自动授权无障碍这段代码，绝不多问打扰。
😀wx：TryNeverStop

**Comment by TonyJiangWJ** [comment]
#13 暂不支持打包，你可以自己尝试AutoX，具体代码兼容适配请自行摸索
无障碍授权的自己看这块代码：
https://github.com/TonyJiangWJ/AutoScriptBase/blob/ecd6bc2d50360ecce5853b78907bef6af1669528/lib/BaseCommonFunctions.js#L421C7-L421C7

**Comment by geekscloud** [comment]
> #13 暂不支持打包，你可以自己尝试AutoX，具体代码兼容适配请自行摸索
> 
> 无障碍授权的自己看这块代码：
> 
> https://github.com/TonyJiangWJ/AutoScriptBase/blob/ecd6bc2d50360ecce5853b78907bef6af1669528/lib/BaseCommonFunctions.js#L421C7-L421C7
> 
> 

成功的把授权这段单独抽出来一个独立js，成功获取无障碍权限感谢，在4.1.0和4.1.1都成功运行
autox 那边就是没法打包才四处找能打包的项目🌚

**Comment by TonyJiangWJ** [comment]
我记得能打包的 你可以去那边问问 它会被淘宝检测 所以我不用它
