### ISSUE TITLE
有联系方式吗？调试不成功

### ISSUE THREAD

**Issue by 60999** [TonyJiangWJ/AutoScriptBase#3]
clone后,连接设备后F5运行失败，找不到某.js文件是什么原因，作者有群吗？

**Comment by TonyJiangWJ** [comment]
没有群，VS CODE相关的你加官方群问吧 我不用那插件。

**Comment by 60999** [comment]
找到原因了，运行的js错了，应该运行main.js。
请问弹出的系统权限对话框如何点击呢？这时候就卡死了。

**Comment by TonyJiangWJ** [comment]
完全没经验吗？不建议玩这一个，这套代码只是框架没有实质性功能
