### ISSUE TITLE
请教一下，如何用AutoJs实现读取并查找Excel文件里面的内容？

### ISSUE THREAD

**Issue by fringew87** [TonyJiangWJ/AutoScriptBase#6]
不好意思，初次使用Github并不熟悉该怎么留言。
我想用AutoJs写个类似于答题的脚本。有题库，是Excel文件，xlsx格式的。
想着是获取到题目内容之后，从题库里面搜索相应的题目，输出答案。

并不是学生，也不为了牟利，就是单位要求工作日在应用内每天答几个题，算是签到了，一方面是了解学习这方面的知识，另一方面算是给自己一点便利。 
感谢。

**Comment by TonyJiangWJ** [comment]
Excel读取需要第三方依赖，这一点相对来说有点复杂，如果题库变动不大直接转换成文本方式用files进行读取就行了，具体存的格式看怎么方便怎么来。
具体实现还是得靠你自己了
