### ISSUE TITLE
huaweip30-EMUI-11-Android-10 授权不成功

### ISSUE THREAD

**Issue by congscallion** [TonyJiangWJ/AutoScriptBase#8]
ENV： huaweip30-EMUI-11-Android-10
log:

PS D:\my\platform-tools> .\adb.exe devices
List of devices attached
8KE0219523025762        device

PS D:\my\platform-tools> .\adb.exe shell pm grant org.autojs.autojs android.permission.WRITE_SECURE_SETTINGS
PS D:\my\platform-tools>

执行后无异常，但打开autojs，执行脚本仍然会要求授权无障碍服务。请问有什么办法可解决？

**Comment by TonyJiangWJ** [comment]
有时候要求授权是bug，你可以多试几次  或者直接到无障碍页面查看是否已经开启了，如果开启了就是正常的

**Comment by congscallion** [comment]
@TonyJiangWJ  换成auto.js M 授权成功了。感谢支持！
