### ISSUE TITLE
我按照文档使用ADB开启权限开启完后为什么还是没反应啊?

### ISSUE THREAD

**Issue by weiouyang** [TonyJiangWJ/AutoScriptBase#9]

**Comment by TonyJiangWJ** [comment]
自己检查一下是否完全按说明操作了，或者你说一下你具体是怎么操作的 不然我可不知道你出的什么问题

**Comment by canghaicode** [comment]
android.permission.WRITE_SECURE_SETTINGS 这个授权似乎不是直接获取无障碍，而是允许设置权限，应该还需要代码来主动设置无障碍才行 参考https://blog.csdn.net/feiyunjs/article/details/93855262

**Comment by here101** [comment]
我也一样没反应，之前按照教程成功了的，后来不知道咋的又需要每回运行时手动开启权限了，然后我又按照教程做，就没反应了，还是需要手动开启权限。
